version: '3.9'

services:
  web:
    build: .
    container_name: django_docx
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media:/app/media
      - sqlite_data:/app/db_data
    ports:
      - "8000:8000"


volumes:
  media:
  sqlite_data:
